### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by jjlao** [DartSuslik42/MoodleHack#1]

**Comment by DartSuslik42** [comment]
На каком этапе расширение дало сбой?

**Comment by jjlao** [comment]
when i am in exam page and ta^p moodle hack extension nothing work u have whatsapp or mail to show you what is the problem exactly ?

**Comment by DartSuslik42** [comment]
Расширение работает только на страницах, которые находятся в домене https://moodle.phystech.edu/
Вот почта для обратной связи : dartsuslik42@gmail.ru
